server.port=8001

spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
spring.datasource.hikari.minimumIdle=2
spring.datasource.hikari.idleTimeout=300000
spring.datasource.hikari.maxLifetime=1800000
spring.datasource.hikari.connectionTestQuery=SELECT 1

spring.jpa.mapping-resources=META-INF/orm-postgresql.xml
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,info

spring.application.name=dictionary

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.audiences=${OAUTH2_AUDIENCE}

de.trinimon.dictionary.cache.enabled=true
de.trinimon.security.enabled=${SECURITY_ENABLED:false}

