server.port=8001

spring.datasource.url=jdbc:postgresql://localhost:5433/dictionaries
spring.datasource.username=${TRANSLATOR_USER}
spring.datasource.password=${TRANSLATOR_PASSWORD}

spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
spring.datasource.hikari.minimumIdle=2
spring.datasource.hikari.idleTimeout=300000
spring.datasource.hikari.maxLifetime=1800000
spring.datasource.hikari.connectionTestQuery=SELECT 1

spring.jpa.mapping-resources=META-INF/orm-postgresql.xml
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,info

spring.application.name=dictionary
de.trinimon.dictionary.cache.enabled=true


