[versions]
spring-boot = "4.0.5"
dependency-management = "1.1.7"
jacoco = "0.8.14"
mapstruct = "1.6.3"
springdoc = "3.0.1"
lombok = "1.18.42"
instancio = "5.5.1"
h2 = "2.4.240"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
dependency-management = { id = "io.spring.dependency-management", version.ref = "dependency-management" }

[libraries]
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache" }
flyway-core = { module = "org.flywaydb:flyway-core" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
postgresql = { module = "org.postgresql:postgresql" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }

spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-data-jpa-test = { module = "org.springframework.boot:spring-boot-starter-data-jpa-test" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-boot-test-autoconfigure = { module = "org.springframework.boot:spring-boot-test-autoconfigure" }
instancio-junit = { module = "org.instancio:instancio-junit", version.ref = "instancio" }

mockito-core = { module = "org.mockito:mockito-core" }
