CREATE SCHEMA IF NOT EXISTS common;

CREATE TABLE IF NOT EXISTS common.translation
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_language VARCHAR(10)   NOT NULL,
    target_language VARCHAR(10)   NOT NULL,
    source          VARCHAR(1024) NOT NULL,
    target          VARCHAR(1024) NOT NULL
);